### ISSUE TITLE
Error Import - with import S3FileUpload from 'react-s3' 

### ISSUE THREAD

**Issue by ken-mf** [Fausto95/aws-s3#56]
I'm getting an error throw regarding an unexpected token, regarding the import Signature from "./Signature"

I'm not sure why, the first time hitting this page this error doesn't show up but on refresh it does.

I'm using `Nextjs` setup, I've tried the `aws-s3` version of this library and that has no issue however I get a different error to do with unable to split file name of undefined.

```
import S3FileUpload from 'react-s3';
// Optional Import
import { uploadFile } from 'react-s3';

```

```
(function (exports, require, module, __filename, __dirname) { import Signature from "./Signature";
                                                                     ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/kwu/projects/c2b--booking-form/node_modules/react-s3/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by ken-mf** [comment]
Wrong repo

**Comment by ken-mf** [comment]
Sorry didn't realise `react-s3` linked back to this repo.

**Comment by Fausto95** [comment]
I've renamed the project, please install `aws-s3` to avoid bugs
